# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for seisplot.py

# Plot the image?
plot: false

# Save the numpy array as npy?
save: true

# Side label side
sidelabel: right

# Traces per inch   (less -> bigger plot)
tpi: 400

# Inches per second (more -> bigger plot)
ips: 50

# Wiggle skips (1 -> no skips, 2 -> every 2nd trace, etc.)
skip: 3

# Seismic data display parameters (wiggle, varden, both):
display: vd

# Multiplication factor for amplitudes 
gain: 1

# Percentile to clip amplitude at for display and for histogram. 
percentile: 99.0

# Wiggle fill: RGB, 0-255, opacity: 0-1
colour: 
  - 255
  - 168
  - 231
opacity: 0.67

# Wiggle plot lineweight
lineweight: 0.1

# Colormap for variable density
# e.g. matplotlib colourbars: Greys (black to white), RdBu, RdGy, RdYlBu, seismic, etc.
# See more at http://matplotlib.org/examples/color/colormaps_reference.html
cmap: seismic

# Fontsize
fontsize: 10

# Watermark
# watermark_text: © A Seismic Company
# watermark_size: 12
# watermark_colour: black
# watermark_rotation: 33  # degrees
# watermark_cols: 4  # in x direction

# Stupid things
stain_paper: no
coffee_rings: 0
scribble: no
